### PR TITLE
update apace-tomcat-on-koding.md

### PR DESCRIPTION
**Pull request by AndreDionisio**
reduce the learn curve by increasing information about the instructions in the terminal.

### CODE REVIEW

**Comment by AndreDionisio** [comment]
Nice

**Comment by leeola** [comment]
@AndreDionisio Appreciate your time on this!

Can you do me a favor and comment a bit on your changes here? I'm trying to decide if some of these changes should be placed into KPM directly, for users who aren't looking at the guide. For example, you linked the tomcat directories to your home directory:

```
ln -s /etc/tomcat7 usrtomcat
ln -s /usr/share/tomcat7 tomcat
```

What is the motivation here?

Appreciate your comments :)

**Comment by AndreDionisio** [comment]
I made this to aid the users to easy send the commands, and easy access the
files in the path linked. So this is a way to have a handy in make the
changes need.

2015-03-16 12:59 GMT-03:00 Lee Olayvar <notifications@github.com>:

> @AndreDionisio <https://github.com/AndreDionisio> Appreciate your time on
> this!
>
> Can you do me a favor and comment a bit on your changes here? I'm trying
> to decide if some of these changes should be placed into KPM directly, for
> users who aren't looking at the guide. For example, you linked the tomcat
> directories to your home directory:
>
> ln -s /etc/tomcat7 usrtomcat
> ln -s /usr/share/tomcat7 tomcat
>
> What is the motivation here?
>
> Appreciate your comments :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koding/kdlearn/pull/71#issuecomment-81759258>.
>



-- 
André Dionisio

**Comment by leeola** [comment]
Gotcha, alright cool :)

**Comment by AndreDionisio** [comment]
Hi,

I&#39;d like to include you in my network to share updates and stay in touch.

- Andre_Luis_Tomaz

Confirm that you know Andre_Luis_Tomaz: https://www.linkedin.com/e/v2?e=-1zx0pg-iak1o8j3-3x&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=aX-XrbVG&amp;invitationID=6012681168124674048


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-1zx0pg-iak1o8j3-3x&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQGWrPF_GjVY_wAAAU3FVwmJ03kfOGOM48RG6lHwZPlZ8K8fbS-zYqa6B5xq_JXV0G1YvHRAXk-Uw-2VuMks6fUis2xyII0SYg574oImJJeYQCpgOpdC-DZKYAm6vw6frZmVK3ld-GbKm7G7TZSIddntyr4YO10aDg_b38wnEeGg296ZzcyriwQBeT896kBg2bvm&amp;eid=-1zx0pg-iak1o8j3-3x Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-1zx0pg-iak1o8j3-3x&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by AndreDionisio** [comment]
Andre_Luis_Tomaz Dionisio would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Ud30QdPoQcz4Udz4Ne3oOcj0Sfkh9rCZFt65QqnpKqip7lC9Om2RoojRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4CrjcJd6cQd39QomAJpT0Mu7ENbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6012681210709438464_500&markAsRead=

View Andre_Luis_Tomaz Dionisio&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6012681210709438464_500&simpleRedirect=6QPhjsBd6cQd39QomB5dOlDs31Uuz55dOkJr6NRryRQu6lQnSlIqmpLsD0Je2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnThPsCBCbmNJpjRIqm5JhmJOt2pQu6lQnSlIqmpLsD0Je2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnThPsCBCbmNJpjRHsDgCcz8Od34OczsZp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mgQdz9ydPcMpmcVdz5xczANp6pypj4Ncj4Mc30Mc30MpCcOej8MdCoPoj4Udm8Mp6cMcjkMoCcSdzxzojoTozxBe68Uc64SdPgOcPkOcC8Rc3oMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwQc3gTdzgOcjwScj4Udz8Nc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCrjcJd6cQd39QomAJpT0Mu7ENbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6012681210709438464_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JcOQQoPgQcDhxqiRDs31Uuz4JfmhFpip1gktAt6l9tRtKu6l1pkpItkJbqzlRgBd8iRZegA5ysDsNuD9MqD5LpChqoSt8rkRhjPxIckNHuAdRrPl2rmJVujwJmDBhkkBGk79jc6oJp4NNdktWekYUcCh5gRtohl9CmANSuj9VpPBjd5xnk7F1um99iP1LuCtzh59qckkQtAFGrPhjr4Bfilx4cAdqtkROonkSrAB8lDFVl31yrPtEek5FhQAQmD51iR5np5xBc6MPlk51gl5Wq31ftPdotTB2hl51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCrjcJd6cQd39QomAJpT0Mu7ENbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6012681210709438464_500&amp;markAsRead=This email was intended for koding/kdlearn. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CrjcJd6cQd39QomAJpT0Mu7ENbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6012681210709438464_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Pull request merged**
