### PR TITLE
swift hello world tutorial

### PR DESCRIPTION
**Pull request by git-bee**

### CODE REVIEW

**Comment by stefanbc** [comment]
@git-bee awesome tutorial on Swift and great update on the Pascal one. There are some things before we can merge.

1. You need to fix your merge conflicts.
2. We may want to split the Swift guide into 2 separate guides. The motivation is this. Beginners will run away if they see such a huge guide. Thus by splitting it we can be more organised.
3. I'll merge it and the make a few minor wording adjustments, if that's ok with you.

**Comment by gniting** [comment]
@stefanbc agree with your recommendation of splitting up the guide. Once this is done, let's get it shared up and maybe even a blog post.
@git-bee awesome work my friend! BTW, you should now have the Koding hobbyist account :) Let us know if that is not the case yet.

**Comment by stefanbc** [comment]
@gniting I'll make a note of that.

**Comment by git-bee** [comment]
Guys… do whatever you want with the raw material from me. It's all yours, I'm fine. If you still need my help with it, I'll do it for you. 😊 

English is not my first language, though I'm not very bad with it, I still do many mistakes here and there. That's why I want you to take a look at it, I know I've done some mistakes.

Yes, I already have the hobbyist plan. Thank you very much! 😊

**Comment by git-bee** [comment]
Btw… how do I resolve the merge conflict? This github web is so confusing. What if you just take the raw text of the article and do whatever you want with it. I'm all fine, even it you want to remove my name from the article, it's all yours. I keep the original text on my own koding account. I better keep myself busy with preparing for the next article. Already got some ideas. 😊

Oh… may I publish my original version of the article? Some people on the Koding Channel had been asking for Swift tutorial. I want to help them. Is that alright?

**Comment by cihangir** [comment]
@kwagdy when you have time please migrate this tut to new system if applicable
thanks for your contribution @git-bee

**Pull request closed without merging**
